import React, {useEffect,useState} from 'react';
import GradingProvider from './GradingProvider';
import {SlidersHorizontal,Save,RotateCcw,LoaderCircle} from 'lucide-react';

export default function AgentPromptSettings({api,current,onSaved,toast,disabled=false}){
  const [draft,setDraft]=useState(''),[builtin,setBuiltin]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[topK,setTopK]=useState(100),[judgeProvider,setJudgeProvider]=useState('jev');
  useEffect(()=>{let alive=true;setReady(false);api('/agent/settings').then(value=>{if(alive){setBuiltin(value.builtin_prompt);setDraft(current?.system_prompt??value.system_prompt);setReady(true);}}).catch(e=>toast(e.message,true));return()=>{alive=false;};},[current?.id,current?.prompt_revision]);
  useEffect(()=>{setTopK(current?.top_k??100);setJudgeProvider(current?.judge_provider??'jev');},[current?.id,current?.top_k,current?.judge_provider]);
  async function save(asDefault=false){setBusy(true);try{const value=await api(asDefault||!current?'/agent/settings':`/chats/${current.id}/settings`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({system_prompt:draft,...(current&&!asDefault?{top_k:Number(topK),judge_provider:judgeProvider,expected_revision:current.prompt_revision}:{})})});if(current&&!asDefault)onSaved(value);toast(asDefault||!current?'Default prompt saved for new conversations.':'Saved. The next turn will use these settings.');}catch(e){toast(e.message,true);}finally{setBusy(false);}}
  return <details className="agent-prompt-settings"><summary><SlidersHorizontal size={14}/>{current?`Conversation system prompt · v${current.prompt_revision??1}`:'Default system prompt'}</summary><label>Agent instructions<textarea aria-label="Agent system prompt" value={draft} maxLength={20000} onChange={e=>setDraft(e.target.value)} disabled={disabled||busy||!ready} rows={10}/></label>{current&&<label>Maximum retrieved chunks<input aria-label="Retrieval limit" type="number" min={1} max={500} value={topK} onChange={e=>setTopK(e.target.value)} disabled={disabled||busy}/></label>}{current&&<GradingProvider label="Conversation file grading" value={judgeProvider} onChange={setJudgeProvider} disabled={disabled||busy}/>}<p>{current?'Changing the prompt starts a new session on the next turn, with the full conversation text. Files are searched or transferred again.':'The default prompt applies to new conversations.'}Past evaluations keep the settings used at that time.</p><div><button className="button primary small-button" disabled={disabled||busy||!ready||!draft.trim()} onClick={()=>save()}>{busy?<LoaderCircle size={13} className="spin"/>:<Save size={13}/>} {current?'Apply to next turn':'Save default'}</button>{current&&<button className="button secondary small-button" disabled={busy||!ready||!draft.trim()} onClick={()=>save(true)}>Use for new conversations</button>}<button className="button secondary small-button" disabled={disabled||busy||!ready} onClick={()=>setDraft(builtin)}><RotateCcw size={12}/>Load built-in prompt</button></div></details>;
}
