import React, { useEffect, useRef, useState } from 'react';
import { Plus, Send, LoaderCircle, Square, Search, FileDown, Terminal, Brain, CheckCheck, AlertTriangle, ChevronDown, MessagesSquare, Radio } from 'lucide-react';
import Markdown from './Markdown';
import { Links } from './Knowledge';
import UsagePanel from './UsagePanel';
import FileScores from './FileScores';
import AgentPromptSettings from './AgentPromptSettings';
import GradingProvider,{gradingName} from './GradingProvider';
import {AnswerEvaluation} from './EvaluationPanel';

const names={idle:'Ready for a question',running:'Running',cancelling:'Cancelling',completed:'Turn completed',failed:'Incomplete',disconnected:'Reconnect to observe',cancelled:'Cancelled'};

function Trace({entries}) {
  const shown=entries.filter(t=>['search_started','retrieval','file_download_started','file_downloaded','file_reused','reasoning','command_execution','lifecycle','environment_wait','cancel_requested','prompt_session_changed','evaluation_capture_failed'].includes(t.kind)||(t.kind==='tool_completed'&&!t.data.success));
  return <div className="trace-list">{shown.length?shown.map(entry=>{
    const d=entry.data;
    if(entry.kind==='search_started')return <section className="trace-card" key={entry.id}><h4><Search size={14}/>Search query</h4><strong className="query-text">{d.query}</strong>{d.library_name&&<p>Library: {d.library_name} · {d.library_id.slice(0,6)}</p>}<p>Retrieve up to {d.top_k} chunks</p>{d.question!==d.query&&<details><summary>Full relevance question</summary><p>{d.question}</p></details>}</section>;
    if(entry.kind==='retrieval'){
      const end=entries.find(t=>t.kind==='search_completed'&&t.data.call_id===d.call_id);
      const files=end?.data.files||entries.filter(t=>t.kind==='file_scored'&&t.data.call_id===d.call_id).map(t=>t.data).sort((a,b)=>(b.score??-1)-(a.score??-1));
      return <section className="trace-card results" key={entry.id}><h4><Search size={14}/>Retrieval & document scoring</h4><div className="retrieval-counts"><span><b>{d.chunk_count}</b> chunks</span><span><b>{d.file_count}</b> documents</span></div><p>{files.length} / {d.file_count} scores received{end?' · Search completed':''}</p><FileScores files={files}/><details className="raw-chunks"><summary>View {d.chunk_count} retrieved chunks</summary>{d.chunks.map(c=><div key={c.id}><strong>{c.name} · chunk {c.number+1}</strong><small>RRF {c.rrf_score.toFixed(4)} · tokens {c.start_token}–{c.end_token}</small><pre>{c.text}</pre></div>)}</details></section>;
    }
    if(entry.kind==='reasoning')return d.text?<details className="trace-card" key={entry.id}><summary><Brain size={14}/>Reasoning summary <ChevronDown size={12}/></summary><Markdown text={d.text}/></details>:null;
    if(entry.kind==='command_execution')return <details className="trace-card" key={entry.id}><summary><Terminal size={14}/>File reads & commands {d.exit_code!=null&&`· exit ${d.exit_code}`}<ChevronDown size={12}/></summary><pre>{d.command}</pre>{d.output&&<pre>{d.output}</pre>}</details>;
    if(entry.kind.startsWith('file_'))return <section className="trace-card" key={entry.id}><h4><FileDown size={14}/>{entry.kind==='file_download_started'?'Downloading source':entry.kind==='file_reused'?'Reusing a file in this conversation':'Transferred to Agent'}</h4><strong>{d.name}</strong><p>{{original:'Original file',parsed:'Complete parsing .md',transcript:'Transcript .md',report:'Complete report .md'}[d.variant]}</p><Links links={[{...d,label:d.provider==='gcs'?'GCS Markdown':d.provider==='local'?'Uploaded source (local)':'Google Drive source'}]}/>{d.path&&<details><summary>File transfer details</summary><code>{d.path}</code><p>{d.size?.toLocaleString()} bytes</p><code>SHA-256 {d.sha256}</code><p>Transfer completed. Later commands show whether the file was read.</p></details>}</section>;
    if(entry.kind==='environment_wait'){const done=d.status==='completed'||entries.some(t=>t.kind==='file_downloaded'&&t.at>entry.at);return <div className="trace-lifecycle" key={entry.id}>{done?<CheckCheck size={12}/>:<LoaderCircle className="spin" size={12}/>} {done?'Agent sandbox connected and ready for files.':d.message}</div>;}
    if(entry.kind==='lifecycle')return <div className="trace-lifecycle" key={entry.id}><Radio size={12}/>{d.event.endsWith('pending')?'Preparing Agent sandbox':'Agent sandbox ready'}</div>;
    return <section className="trace-card error-text" key={entry.id}><h4><AlertTriangle size={14}/>{d.name||'Activity'}</h4><p>{d.error||d.message}</p></section>;
  }):<div className="trace-empty"><Radio size={26}/><p>Searches, document scores, file transfers, and reasoning summaries appear here as the Agent works.</p><small>Summaries are provided by the model and may not appear on every turn.</small></div>}</div>;
}

export default function ChatPanel({api,toast,onOpenEvaluations}) {
  const [chats,setChats]=useState([]), [selected,setSelected]=useState(()=>localStorage.getItem('folio-chat')||null);
  const [current,setCurrent]=useState(null), [model,setModel]=useState('gpt-6.1-sol'), [models,setModels]=useState(['gpt-6.1-sol']);
  const [topK,setTopK]=useState(100), [text,setText]=useState(''), [busy,setBusy]=useState(false), [connected,setConnected]=useState(false);
  const [libraries,setLibraries]=useState([]), [libraryId,setLibraryId]=useState(()=>localStorage.getItem('folio-library')||'');
  const [evaluations,setEvaluations]=useState([]),[judgeProvider,setJudgeProvider]=useState(()=>localStorage.getItem('folio-chat-judge')==='openai_decisions'?'openai_decisions':'jev');
  useEffect(()=>{let alive=true;setEvaluations([]);if(!selected)return;async function update(){try{const d=await api(`/evaluations?chat_id=${selected}&limit=100`);if(alive)setEvaluations(d.records);}catch{}}update();const timer=setInterval(update,3000);return()=>{alive=false;clearInterval(timer);};},[selected]);
  const scroll=useRef(), stick=useRef(true), selectedRef=useRef(selected);
  function selectChat(id){selectedRef.current=id;setSelected(id);setCurrent(null);if(!id)localStorage.removeItem('folio-chat');const c=chats.find(c=>c.id===id);if(c?.library_id)setLibraryId(c.library_id);}
  function accept(value){if(value.id===selectedRef.current){setCurrent(previous=>previous?.id===value.id&&previous.revision>value.revision?previous:value);if(value.library_id)setLibraryId(value.library_id);}}
  async function refresh(){const [list,data]=await Promise.all([api('/chats'),api('/knowledge')]);setChats(list);setLibraries(data.libraries);setLibraryId(id=>data.libraries.some(l=>l.id===id)?id:data.libraries[0]?.id||'');}
  useEffect(()=>{refresh().catch(e=>toast(e.message,true));api('/agent/models').then(d=>{setModels(d.models);setModel(d.default);if(d.error)toast(d.error,true);}).catch(e=>toast(e.message,true));const timer=setInterval(()=>refresh().catch(()=>{}),3000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(libraryId)localStorage.setItem('folio-library',libraryId);},[libraryId]);
  useEffect(()=>{
    setCurrent(null);setConnected(false);stick.current=true;
    if(!selected)return;
    localStorage.setItem('folio-chat',selected);
    const events=new EventSource(`/api/chats/${selected}/events`);
    events.addEventListener('state',event=>{accept(JSON.parse(event.data));if(selectedRef.current===selected)setConnected(true);});
    events.onopen=()=>setConnected(true);events.onerror=()=>setConnected(false);
    api(`/chats/${selected}`).then(accept).catch(e=>{if(selectedRef.current===selected){toast(e.message,true);selectChat(null);localStorage.removeItem('folio-chat');}});
    return()=>events.close();
  },[selected]);
  useEffect(()=>{if(stick.current&&scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;},[current?.revision]);
  async function newChat(){setBusy(true);try{const c=await api('/chats',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({library_id:libraryId,model,top_k:Number(topK),judge_provider:judgeProvider})});selectChat(c.id);setText('');await refresh();}catch(e){toast(e.message,true);}finally{setBusy(false);}}
  async function send(event){event.preventDefault();if(!text.trim()||busy||current?.read_only||!libraryId||(selected&&!current))return;setBusy(true);const draft=text;try{let id=selected;if(!id){const c=await api('/chats',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({library_id:libraryId,model,top_k:Number(topK),judge_provider:judgeProvider})});id=c.id;selectChat(id);}const value=await api(`/chats/${id}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:draft})});accept(value);setText('');stick.current=true;await refresh();}catch(e){toast(e.message,true);}finally{setBusy(false);}}
  async function control(action){setBusy(true);try{accept(await api(`/chats/${selected}/${action}`,{method:'POST'}));}catch(e){toast(e.message,true);}finally{setBusy(false);}}
  const running=['running','queued','cancelling'].includes(current?.status);
  const library=libraries.find(l=>l.id===libraryId);
  const history=chats.filter(c=>c.library_id===libraryId), legacy=chats.filter(c=>!c.library_id);
  const readOnly=current?.read_only;
  return <section className="chat-workspace panel">
    <aside className="chat-sidebar"><div className="new-chat-settings"><label>Conversation library<select aria-label="Conversation library" value={libraryId} onChange={e=>{selectChat(null);setLibraryId(e.target.value);setText('');}}>{!libraries.length&&<option value="">Import a Drive folder or ZIP first</option>}{libraries.map(l=><option key={l.id} value={l.id}>{l.name} · {l.id.slice(0,6)}</option>)}</select></label><p className="library-scope-note">{library?`${library.indexed_files} documents · ${library.chunks} chunks`:'No libraries yet'}<br/>Each conversation stays within this library.</p><label>Model for new conversations<select aria-label="Model for new conversations" value={model} onChange={e=>setModel(e.target.value)}>{models.map(m=><option key={m}>{m}</option>)}</select></label><label>Retrieved chunk limit<input type="number" aria-label="Retrieved chunk limit" min={1} max={500} value={topK} onChange={e=>setTopK(e.target.value)}/></label><GradingProvider label="File grading for new conversations" value={judgeProvider} onChange={value=>{setJudgeProvider(value);localStorage.setItem('folio-chat-judge',value);}} disabled={busy}/><button className="button primary" disabled={busy||!libraryId} onClick={newChat}><Plus size={16}/>New conversation</button></div><div className="chat-list-label">Library conversations</div><div className="chat-history">{history.length?history.map(c=><button className={selected===c.id?'selected':''} key={c.id} onClick={()=>selectChat(c.id)}><strong>{c.title}</strong><small>{names[c.status]||c.status}</small></button>):<p className="subtle-label">Send your first question to start a conversation.</p>}{legacy.length>0&&<details className="legacy-chats"><summary>Legacy conversation · Read only</summary>{legacy.map(c=><button className={selected===c.id?'selected':''} key={c.id} onClick={()=>selectChat(c.id)}><strong>{c.title}</strong></button>)}</details>}</div></aside>
    <div className="conversation"><header className="conversation-header"><div><MessagesSquare size={18}/><strong>{current?.title||'Explore your documents'}</strong></div><p className="conversation-library">{readOnly?'Legacy conversation · Read only':`Library: ${current?.library_name||library?.name||'Choose'}${libraryId?' · '+libraryId.slice(0,6):''}`}</p><small>{current?.model||model}{current&&` · top ${current.top_k} chunks · ${gradingName(current.judge_provider)}`}</small><AgentPromptSettings api={api} current={current} onSaved={accept} toast={toast} disabled={running||current?.response_active||readOnly||current?.status==='disconnected'}/></header>
      <div className="messages" ref={scroll} onScroll={()=>{if(scroll.current)stick.current=scroll.current.scrollHeight-scroll.current.scrollTop-scroll.current.clientHeight<90;}}>{current?.messages.length?current.messages.map(m=><section className={`chat-message ${m.role} ${m.phase||''}`} key={m.id}><div className="message-author">{m.role==='user'?'You':m.phase==='final_answer'?'Folio · Answer':'Folio · Progress'}</div>{m.role==='user'?<p>{m.text}</p>:<Markdown text={m.text}/>} {m.phase==='final_answer'&&<AnswerEvaluation record={evaluations.find(r=>r.turn_id===m.turn_id)} onOpen={onOpenEvaluations}/>}</section>):<div className="conversation-empty"><div className="chat-orbit"><Search size={27}/></div><h2>Answers with a path to the source.</h2><p>Search your documents, compare relevance, and let the Agent read the original, report, or transcript.</p><button onClick={()=>setText('Find documents about RAG retrieval. List their names, relevance, and source links.')}>Find documents about RAG retrieval <Send size={13}/></button></div>}{running&&<div className="agent-working"><LoaderCircle size={15} className="spin"/>Agent is working. Follow the activity log on the right.</div>}</div>
      {readOnly&&<div className="chat-error"><AlertTriangle size={16}/><span>This legacy conversation used mixed data. Select a library and start a new conversation to keep sources isolated.</span></div>}
      {current?.error&&!readOnly&&<div className="chat-error"><AlertTriangle size={16}/><span>{current.error}</span>{current.status==='disconnected'&&<button className="button secondary small-button" onClick={()=>control('resume')} disabled={busy}>Reconnect</button>}</div>}
      <form className="composer" onSubmit={send}><textarea aria-label="Ask about your documents" value={text} disabled={readOnly||!libraryId||(!!selected&&!current)} onChange={e=>setText(e.target.value)} placeholder={readOnly?'This conversation is read only. Start a new one in a library.':current?.messages.length?'Ask a follow-up, compare sources, or request more evidence…':'Ask about this library, or ask the Agent to find a file…'} rows={3} maxLength={16000} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(!running&&current?.status!=='disconnected')send(e);}}}/><div className="composer-footer"><span>{selected?<><i className={connected?'online':'offline'}/>{connected?'Live activity connected':'Reconnecting'} · {readOnly?'Read only':names[current?.status]||'Loading'}</>:'Shift + Enter new line · Conversation saved automatically'}</span>{running&&!readOnly?<button type="button" className="button secondary small-button" onClick={()=>control('cancel')} disabled={busy||!current?.session_id}><Square size={12}/>Stop</button>:<button className="button primary small-button" type="submit" disabled={busy||readOnly||!libraryId||(!!selected&&!current)||!text.trim()||current?.status==='disconnected'||current?.response_active}>{busy?<LoaderCircle className="spin" size={15}/>:<Send size={15}/>}Send</button>}</div></form>
    </div>
    <aside className="execution-trace"><header><strong><Radio size={16}/>Activity log</strong><small>{current?.trace.length||0} events</small></header>{current&&<UsagePanel api={api} chatId={current.id} turnId={current.turn_id} running={running} compact/>}<Trace entries={current?.trace||[]}/>{current?.session_id&&<details className="session-ids"><summary>Session and turn</summary><code>{current.session_id}</code><code>{current.turn_id}</code></details>}</aside>
  </section>;
}
