import React, { useEffect, useState } from 'react';
import { Database, RefreshCw, ExternalLink, FileText, CheckCheck, AlertTriangle, LoaderCircle, X, Download } from 'lucide-react';
import Markdown from './Markdown';
import UsagePanel from './UsagePanel';

const labels = {ready:'Indexed', pending:'Pending', indexing:'Indexing', uploaded:'Uploaded', uploading:'Uploading', failed:'Retry needed', interrupted:'Interrupted', queued:'Queued', running:'Processing', completed:'Completed', partial:'Partially incomplete'};
export function State({value}) { return <span className={`kb-state ${value}`}><i/>{labels[value] || value}</span>; }
export function Links({links=[], documentId, libraryId}) {
  const [renewed,setRenewed]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const shown=renewed||links;
  const expires=shown.find(l=>l.expires_at)?.expires_at;
  async function renew(){setBusy(true);setError('');try{const r=await fetch(`/api/knowledge/${documentId}/links?library_id=${libraryId}`);const value=await r.json();if(!r.ok)throw Error(value.detail||'Could not refresh links');setRenewed(value.links);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <div><div className="source-links">{shown.map(link=>link.url?<React.Fragment key={link.variant}><a href={link.url} target="_blank" rel="noreferrer" title={link.provider==='gcs'?'Open the complete Markdown text':undefined}>{link.label}<ExternalLink size={11}/></a>{link.download_url&&<a href={link.download_url} target="_blank" rel="noreferrer" aria-label={`Download ${link.label}`}><Download size={11}/>Download</a>}</React.Fragment>:<span key={link.variant} title={link.local_only?'Original is available inside this Folio workspace':link.error||'Links become available after upload'}>{link.label} · {link.local_only?'Local file':link.error?'Retry link':'Pending upload'}</span>)}</div>{expires&&<small className="link-expiry">GCS links expire at {new Date(expires).toLocaleString('en-US')}{documentId&&libraryId&&<button disabled={busy} onClick={renew}>{busy?'Refreshing…':'Refresh links'}</button>}</small>}{error&&<small className="error-text">{error}</small>}</div>;
}

function CloudStorage({bucket,api,toast,onSave}) {
  const [value,setValue]=useState(bucket||''),[busy,setBusy]=useState(false),[result,setResult]=useState(null);
  useEffect(()=>{setValue(bucket||'');},[bucket]);
  async function save(){setBusy(true);try{await api('/storage/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bucket:value})});setResult(await api('/storage/test',{method:'POST'}));await onSave();}catch(e){toast(e.message,true);}finally{setBusy(false);}}
  return <section className="panel cloud-storage"><div><h2>Cloud Markdown</h2><p>Originals stay in Drive or on this server for ZIP imports. Complete Markdown, transcripts, and reports are stored in private GCS with links valid for about 24 hours.</p></div><div className="cloud-storage-form"><label htmlFor="gcs-bucket">GCS bucket</label><input id="gcs-bucket" value={value} onChange={e=>setValue(e.target.value)} placeholder="Enter an existing bucket name"/><button className="button secondary" disabled={busy||!value.trim()} onClick={save}>{busy?<LoaderCircle size={15} className="spin"/>:<CheckCheck size={15}/>}Save & test</button></div>{result&&<p className={result.connected?'cloud-connected':'error-text'}>{result.message}</p>}<small>Uses the service account in Connections & models. After setup, select Update library to upload existing results.</small></section>;
}

export default function Knowledge({api, toast, onChat, onSearch}) {
  const [data,setData]=useState(null), [busy,setBusy]=useState(false), [connection,setConnection]=useState(null);
  const [query,setQuery]=useState(''), [preview,setPreview]=useState(null), [content,setContent]=useState(null);
  const [libraryId,setLibraryId]=useState(()=>localStorage.getItem('folio-library')||'');
  async function refresh(){const value=await api('/knowledge');setData(value);setLibraryId(id=>value.libraries.some(l=>l.id===id)?id:value.libraries[0]?.id||'');}
  useEffect(()=>{refresh().catch(e=>toast(e.message,true));const timer=setInterval(()=>refresh().catch(()=>{}),1800);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(libraryId)localStorage.setItem('folio-library',libraryId);setConnection(null);setQuery('');setPreview(null);},[libraryId]);
  useEffect(()=>{if(!preview)return;const key=e=>{if(e.key==='Escape')setPreview(null);};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[preview]);
  async function build(){setBusy(true);try{await api('/knowledge/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_id:libraryId})});await refresh();toast('Updating the selected library. Completed parsing, reports, and indexes will be reused.');}catch(e){toast(e.message,true);}finally{setBusy(false);}}
  async function test(){setBusy(true);try{setConnection(await api(`/knowledge/test?library_id=${libraryId}`,{method:'POST'}));}catch(e){toast(e.message,true);}finally{setBusy(false);}}
  async function show(doc,variant){setPreview({doc,variant});setContent(null);try{setContent(await api(`/knowledge/${doc.id}/markdown?library_id=${doc.library_id}&variant=${variant}`));}catch(e){toast(e.message,true);}}
  function download(){const url=URL.createObjectURL(new Blob([content.text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=content.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const library=data?.libraries.find(l=>l.id===libraryId);
  const members=(data?.documents||[]).filter(d=>d.library_id===libraryId);
  const docs=members.filter(d=>d.name.toLowerCase().includes(query.toLowerCase()));
  const builds=(data?.builds||[]).filter(b=>b.job_id===libraryId||(!b.job_id&&['queued','running'].includes(b.status)));
  const active=builds.filter(b=>['queued','running'].includes(b.status));
  const latest=active[0]||builds.at(-1);
  const settings=data?.settings;
  return <div className="knowledge-view">
    {settings&&<CloudStorage bucket={settings.gcs_bucket} api={api} toast={toast} onSave={refresh}/>}
    <section className="panel library-picker"><div><label htmlFor="knowledge-library">Select library</label><select id="knowledge-library" value={libraryId} onChange={e=>setLibraryId(e.target.value)}>{!data?.libraries.length&&<option value="">No imports yet</option>}{data?.libraries.map(l=><option key={l.id} value={l.id}>{l.name} · {l.id.slice(0,6)}</option>)}</select><p>Every Drive or ZIP import creates an isolated library, even when importing the same source again.</p>{library?.source_url&&<a href={library.source_url} target="_blank" rel="noreferrer">Open source folder <ExternalLink size={12}/></a>}</div><div className="library-actions"><button className="button secondary" disabled={!library?.indexed_files} onClick={()=>onSearch(libraryId)}>Search this library</button><button className="button primary" disabled={!library?.indexed_files} onClick={()=>onChat(libraryId)}>Chat with this library</button></div></section>
    <section className="kb-overview panel"><div className="kb-overview-title"><span className="kb-symbol"><Database size={25}/></span><div><h2>{library?.name||'Create your first library'}</h2><p>{library?`Imported ${new Date(library.created_at).toLocaleString('en-US')}`:'Import a Drive folder or ZIP archive and finish processing.'}</p></div></div><div className="kb-overview-numbers"><div><strong>{library?.indexed_files??0}</strong><span>Indexed files</span></div><div><strong>{library?.chunks??0}</strong><span>Searchable chunks</span></div><div><strong>{members.filter(d=>d.storage_status==='uploaded').length}</strong><span>Stored in GCS</span></div></div></section>
    <section className="panel kb-controls"><div><h2>Library processing</h2><p>Retry unfinished storage and indexing for this library.</p></div><div className="kb-buttons"><button className="button secondary" disabled={busy||!library} onClick={test}><Database size={15}/>Test Qdrant</button><button className="button primary" disabled={busy||!library||active.length>0} onClick={build}>{busy||active.length?<LoaderCircle size={16} className="spin"/>:<RefreshCw size={16}/>}Update library</button></div></section>
    {connection&&(!connection.library_id||connection.library_id===libraryId)&&<div className={`kb-callout ${connection.connected?'':'warning'}`}>{connection.connected?<CheckCheck size={17}/>:<AlertTriangle size={17}/>}<span>{connection.message}{connection.connected&&` Current: ${connection.points} vector points.`}</span></div>}
    {latest&&<section className="panel build-progress"><div><strong>{latest.current||'Latest library build'}</strong><State value={latest.status}/><span>{latest.completed} / {latest.total} files</span></div><progress max={latest.total||1} value={latest.completed}/>{latest.errors?.length>0&&<details><summary>{latest.errors.length} files need a retry</summary>{latest.errors.map((e,i)=><p key={i}><strong>{e.name}</strong>：{e.error}</p>)}</details>}{latest.error&&<p className="error-text">{latest.error}</p>}</section>}
    <section className="panel kb-documents"><div className="section-head"><h2>Documents & cloud links <span className="count-pill">{docs.length}</span></h2><input className="kb-filter" aria-label="Filter library documents" placeholder="Search filenames…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
      {docs.length?<div className="kb-table-wrap"><table className="kb-table"><thead><tr><th>Document & full content</th><th>GCS upload</th><th>Qdrant index</th><th>Open / download</th></tr></thead><tbody>{docs.map(doc=><tr key={doc.id}><td><button className="kb-file-button" onClick={()=>show(doc,doc.media?'report':'parsed')}><FileText size={19}/><span><strong>{doc.name}</strong><small>{doc.media?'Complete report + transcript':'Complete page-by-page Markdown'} · {doc.content_chars?.toLocaleString()} characters</small></span></button><div className="kb-preview-buttons">{doc.media&&<button onClick={()=>show(doc,'transcript')}>View transcript</button>}<span>Source version {doc.source_version||'—'}</span></div></td><td><State value={doc.storage_status}/>{doc.storage_error&&<details className="inline-error"><summary>View details</summary>{doc.storage_error}</details>}</td><td><State value={doc.index_status}/><small className="chunk-progress">{doc.index_status==='indexing'?`${doc.chunks_done||0} / `:''}{doc.chunk_count||0} chunks</small>{doc.index_error&&<details className="inline-error"><summary>View details</summary>{doc.index_error}</details>}</td><td><Links links={doc.links} documentId={doc.id} libraryId={libraryId}/></td></tr>)}</tbody></table></div>:<div className="kb-empty"><Database size={32}/><h3>{query?'No matching filenames':'No processed documents yet'}</h3><p>Finish processing this import in the workbench. For completed batches, select Update library.</p></div>}
    </section>
    {libraryId&&<UsagePanel api={api} jobId={libraryId} running={active.length>0} title="Library processing costs"/>}
    <details className="panel kb-settings"><summary>Indexing & scoring settings</summary><div className="kb-setting-grid"><div><span>Isolated collection</span><strong>Qdrant · {settings?.qdrant_mode==='server'?'Server':'Local persistent storage'}</strong><code>{library?.collection||'—'}</code></div><div><span>Per chunk</span><strong>512 tokens · 128-token overlap</strong><small>The full filename is prefixed; UTF-8 character boundaries are preserved.</small></div><div><span>Embedding model</span><strong>text-embedding-3-large</strong><small>3072 dimensions · native RRF fusion of dense + BM25</small></div><div><span>Full-document relevance scoring</span><strong>{settings?.jev_model} · Score</strong><small>OpenAI Decisions · {settings?.decisions_model||'gpt-6-luna'}<br/>{settings?.decisions_configured?'OpenAI key configured':'OpenAI key not configured'}<br/>{settings?.jev_configured?'JEV key configured':'JEV_API_KEY not configured'} · 0–3 scale</small></div></div><p>Documents keep their original and complete parsing. Media keeps its original, transcript, and report. Markdown is uploaded to GCS by the service account. Local Markdown staging is removed after verification and indexing; failed uploads remain available for retry.</p></details>
    {preview&&<div className="modal-backdrop" onClick={()=>setPreview(null)}><section className="kb-preview panel" role="dialog" aria-modal="true" aria-label="Full Markdown preview" onClick={e=>e.stopPropagation()}><header><div><h2>{preview.doc.name}</h2><p>{preview.variant==='transcript'?'Full transcript':preview.variant==='report'?'Complete report':'Complete page-by-page parsing'}</p></div><button className="button secondary small-button" disabled={!content} onClick={download}><Download size={15}/>Download .md</button><button className="icon-button" aria-label="Close Markdown preview" onClick={()=>setPreview(null)}><X size={20}/></button></header><div className="kb-preview-body">{content?<Markdown text={content.text}/>:<LoaderCircle className="spin"/>}</div></section></div>}
  </div>;
}
